---
- name: install start and enable httpd
  hosts: 192.168.50.103
  tasks:
    - name: install package
      package:
        name: httpd
        state: latest
    - name: start and enable service
      service:
        name: httpd
        state: starated
        enabled: yes
