---
- name: install start and enable httpd
  hosts: 192.168.50.103
  tasks:
    - name: install package
      package:
        name: apache2
        state: latest
    - name: start and enable service
      service:
        name: apache2
        state: started
        enabled: yes
- name: test httpd accessibility
  become: false
  hosts: 192.168.50.103
  tasks:
    - name: test httpd access
      uri:
        url: http://192.168.50.103
