---
- name: Installing httpd
  hosts: localhost
  become: true
  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present
    - name: Starting the service
      service:
        name: httpd
        state: started
